- members/U02CDRR78MN/kakao2018/1차/뉴스클러스터링.js
- members/U02CDRR78MN/kakao2018/1차/다트게임.js
- members/U02CDRR78MN/kakao2018/1차/비밀지도.js
- members/U02CDRR78MN/kakao2018/1차/셔틀버스.js
- members/U02CDRR78MN/kakao2018/1차/추석트래픽.js
- members/U02CDRR78MN/kakao2018/1차/캐시.js
- members/U02CDRR78MN/kakao2018/1차/프렌즈4블록.js
- members/U02CDRR78MN/kakao2018/3차/n진수게임.js
- members/U02CDRR78MN/kakao2018/3차/방금그곡.js
- members/U02CDRR78MN/kakao2018/3차/압축.js
- members/U02CDRR78MN/kakao2018/3차/자동완성.js
- members/U02CDRR78MN/kakao2018/3차/파일명정렬.js
> 창현 : KAKAO 2018

- members/U02BQ6G1SQJ/programmers/problem/불량 사용자.py
- members/U02BQ6G1SQJ/programmers/problem/크레인 인형뽑기 게임.py
- members/U02BQ6G1SQJ/programmers/problem/튜플.py
<head>
<style>
</style>
</head>
2019 카카오 개발자 겨울 인턴십   > 크레인 인형뽑기 게임 |   |   | Level 1 |   | 08/23(Mon)
2019 카카오 개발자 겨울 인턴십 > 튜플 |   |   | Level 2 |   | 08/23(Mon)
2019 카카오 개발자 겨울 인턴십 > 불량 사용자 |   |   | Level 3 |   | 08/23(Mon)
</body>
</html>
> 2021/08/23 Jade

- members/U02BQ6G1SQJ/programmers/problem/징검다리 건너기.py
- members/U02BQ6G1SQJ/programmers/problem/호텔 방 배정.py
<head>
<style>
</style>
</head>
2019 카카오   개발자 겨울 인턴십 > 호텔 방 배정 |   |   | Level 4 |   | 08/24(Tue)
2019 카카오 개발자 겨울 인턴십 > 징검다리 건너기 |   |   | Level 3 |   | 08/24(Tue)
</body>
</html>
> 2021.08.24 Jade

- members/U02BQ6G1SQJ/programmers/problem/실패율.py
- members/U02BQ6G1SQJ/programmers/problem/오픈채팅방.py
- members/U02BQ6G1SQJ/programmers/problem/후보키.py
<head>
<style>
</style>
</head>
2019   KAKAO BLIND RECRUITMENT > 오픈채팅방 |   |   | Level 2 |   | 08/25(Wed)
2019 KAKAO BLIND RECRUITMENT > 실패율 |   |   | Level 1 |   | 08/25(Wed)
2019   KAKAO BLIND RECRUITMENT > 후보키 |   |   | Level 2 |   | 08/25(Wed)
</body>
</html>
> 2021-08-25 Jade

- members/U02BQ6G1SQJ/programmers/problem/매칭 점수.py
- members/U02BQ6G1SQJ/programmers/problem/블록 게임.py
<head>
<style>
</style>
</head>
2019   KAKAO BLIND RECRUITMENT > 매칭 점수 |   |   | Level 3 |   | 08/27(Fri)
2019   KAKAO BLIND RECRUITMENT > 블록 게임 |   |   | Level 4 |   | 08/27(Fri)
</body>
</html>
> 2021-08-29 Jade

- members/U02BQ6G1SQJ/programmers/problem/보석 쇼핑.py
- members/U02BQ6G1SQJ/programmers/problem/수식 최대화.py
- members/U02BQ6G1SQJ/programmers/problem/키패드 누르기.py
<head>
<style>
</style>
</head>
2020 카카오   인턴십 > 키패드 누르기 |   |   | Level 1 |   | 08/30(Mon)
2020 카카오   인턴십 > 수식 최대화 |   |   | Level 2 |   | 08/30(Mon)
2020 카카오   인턴십 > 보석 쇼핑 |   |   | Level 3 |   | 08/30(Mon)
</body>
</html>
> 2021-08-30 Jade

- members/U02BQ6G1SQJ/programmers/problem/경주로 건설.py
- members/U02BQ6G1SQJ/programmers/problem/동굴 탐험.py
<head>
<style>
</style>
</head>
2020 카카오   인턴십 > 경주로 건설 |   |   | Level 3 |   | 08/31(Tue)
2020 카카오   인턴십 > 동굴 탐험 |   |   | Level 4 |   | 08/31(Tue)
</body>
</html>
> 2021-08-31 Jade

- members/U02BQ6G1SQJ/programmers/problem/괄호 변환.py
- members/U02BQ6G1SQJ/programmers/problem/문자열 압축.py
- members/U02BQ6G1SQJ/programmers/problem/자물쇠와 열쇠.py
<head>
<style>
</style>
</head>
2020   KAKAO BLIND RECRUITMENT > 문자열 압축 |   |   | Level 2 |   | 09/01(Wed)
2020   KAKAO BLIND RECRUITMENT > 괄호 변환 |   |   | Level 2 |   | 09/01(Wed)
2020   KAKAO BLIND RECRUITMENT > 자물쇠와 열쇠 |   |   | Level 3 |   | …
> 2021-09-01 Jade

- members/U02BQ6G1SQJ/programmers/problem/가사 검색.py
- members/U02BQ6G1SQJ/programmers/problem/기둥과 보 설치.py
<head>
<style>
</style>
</head>
2020   KAKAO BLIND RECRUITMENT > 가사 검색 |   |   | Level 4 |   | 09/02(Thu)
2020   KAKAO BLIND RECRUITMENT > 기둥과 보 설치 |   |   | Level 3 |   | 09/02(Thu)
</body>
</html>
> 2021-09-02 Jade

- members/U02BQ6G1SQJ/programmers/problem/블록 이동하기.py
- members/U02BQ6G1SQJ/programmers/problem/외벽 점검.py
<head>
<style>
</style>
</head>
2020   KAKAO BLIND RECRUITMENT > 외벽 점검 |   |   | Level 3 |   | 09/03(Fri)
2020   KAKAO BLIND RECRUITMENT > 블록 이동하기 |   |   | Level 3 |   | 09/03(Fri)
</body>
</html>
> 2021-09-03 Jade

- members/U02BQ6G1SQJ/programmers/problem/거리두기 확인하기.py
- members/U02BQ6G1SQJ/programmers/problem/숫자 문자열과 영단어.py
- members/U02BQ6G1SQJ/programmers/problem/표 편집.py
<head>
<style>
</style>
</head>
2021 카카오   채용연계형 인턴십 > 숫자 문자열과 영단어 |   |   | Level 1 |   | 09/06(Mon)
2021 카카오   채용연계형 인턴십 > 거리두기 확인하기 |   |   | Level 2 |   | 09/06(Mon)
2021 카카오   채용연계형 인턴십 > 표 편집 |   |   | Level 3 |   | 09/06(Mon)
</body> …
> 2021-09-06 Jade

- members/U02BQ6G1SQJ/programmers/problem/메뉴 리뉴얼.py
- members/U02BQ6G1SQJ/programmers/problem/순위 검색.py
- members/U02BQ6G1SQJ/programmers/problem/신규 아이디 추천.py
<head>
<style>
</style>
</head>
2021   KAKAO BLIND RECRUITMENT > 신규 아이디 추천 |   |   | Level 1 |   | 09/08(Wed)
2021   KAKAO BLIND RECRUITMENT > 메뉴 리뉴얼 |   |   | Level 2 |   | 09/08(Wed)
2021   KAKAO BLIND RECRUITMENT > 순위 검색 |   |   | Level 2 |   …
> 2021-09-08 Jade

- members/U02BQ6G1SQJ/programmers/problem/광고 삽입.py
- members/U02BQ6G1SQJ/programmers/problem/합승 택시 요금.py
<head>
<style>
</style>
</head>
2021   KAKAO BLIND RECRUITMENT > 합승 택시 요금 |   |   | Level 3 |   | 09/09(Thu)
2021   KAKAO BLIND RECRUITMENT > 광고 삽입 |   |   | Level 3 |   | 09/09(Thu)
</body>
</html>
> 2021-09-09 Jade

- members/U02BQ6G1SQJ/programmers/problem/매출 하락 최소화.py
- members/U02BQ6G1SQJ/programmers/problem/카드 짝 맞추기.py
<head>
<style>
</style>
</head>
2021   KAKAO BLIND RECRUITMENT > 카드 짝 맞추기 |   |   | Level 3 |   | 09/10(Fri)
2021   KAKAO BLIND RECRUITMENT > 매출 하락 최소화 |   |   | Level 4 |   | 09/10(Fri)
</body>
</html>
> 2021-09-10 Jade

- members/U02BQ6G1SQJ/leetcode/Math/leetcode1041.py
- members/U02BQ6G1SQJ/leetcode/SQL/leetcode1270.sql
- members/U02BQ6G1SQJ/programmers/problem/빛의 경로 사이클.py
- members/U02BQ6G1SQJ/programmers/problem/없는 숫자 더하기.py
<head>
<style>
</style>
</head>
1041. Robot   Bounded In Circle |   | 54.80% | Medium | 1 | 09/14(Tue)
1270. All   People Report to the Given Manager |   | 88.20% | Medium | 1 | 09/14(Tue)
</body>
</html>
> 2021-09-14 Jade

- members/U02BQ6G1SQJ/leetcode/Array/leetcode56.py
- members/U02BQ6G1SQJ/leetcode/Hash_Table/leetcode146.py
<head>
<style>
</style>
</head>
146. LRU Cache |   | 37.20% | Medium | 1 | 09/15(Wed)
56. Merge Intervals |   | 42.10% | Medium | 2 | 09/15(Wed)
</body>
</html>
> 2021-09-15 Jade

- members/U02BQ6G1SQJ/leetcode/Array/leetcode200.py
- members/U02BQ6G1SQJ/leetcode/Hash_Table/leetcode981.py
<head>
<style>
</style>
</head>
981. Time   Based Key-Value Store |   | 54.40% | Medium | 2 | 09/16(Thu)
200. Number of   Islands |   | 50.50% | Medium | 3 | 09/16(Thu)
</body>
</html>
> 2021-09-16 Jade

- members/U02BQ6G1SQJ/leetcode/Array/leetcode253.py
- members/U02BQ6G1SQJ/leetcode/String/leetcode1249.py
<head>
<style>
</style>
</head>
1249. Minimum   Remove to Make Valid Parentheses |   | 64.50% | Medium | 4 | 09/17(Fri)
253. Meeting Rooms   II |   | 47.60% | Medium | 4 | 09/17(Fri)
</body>
</html>
> 2021-09-17 Jade

- members/U02BQ6G1SQJ/leetcode/Array/leetcode1048.py
- members/U02BQ6G1SQJ/leetcode/String/leetcode394.py
<head>
<style>
</style>
</head>
394. Decode String |   | 53.60% | Medium | 4 | 09/18(Sat)
1048. Longest   String Chain |   | 56.30% | Medium | 6 | 09/18(Sat)
</body>
</html>
> 2021-09-18 Jade

- members/U02BQ6G1SQJ/leetcode/Array/leetcode238.py
- members/U02BQ6G1SQJ/leetcode/Array/leetcode973.py
<head>
<style>
</style>
</head>
238. Product   of Array Except Self |   | 61.70% | Medium | 6 | 09/22(Wed)
973. K   Closest Points to Origin |   | 65.00% | Medium | 7 | 09/22(Wed)
</body>
</html>
> 2021-09-22 Jade

- members/U02BQ6G1SQJ/BOJ/implementation/BOJ5430.py
- members/U02BQ6G1SQJ/BOJ/mathematics/BOJ2475.py
<head>
<style>
</style>
</head>
2475. 검증수 STANDARD |   |   | Class 1 |   | 09/26(Sun)
5430. AC STANDARD |   |   | Class 3 |   | 09/26(Sun)
</body>
</html>
> 2021-09-26 Jade

- members/U02BQ6G1SQJ/leetcode/Array/leetcode380.py
- members/U02BQ6G1SQJ/leetcode/Array/leetcode560.py
<head>
<style>
</style>
</head>
380. Insert   Delete GetRandom O(1) |   | 49.60% | Medium | 8 | 09/27(Mon)
560. Subarray   Sum Equals K |   | 43.70% | Medium | 8 | 09/27(Mon)
</body>
</html>
> 2021-09-27 Jade

- members/U02BQ6G1SQJ/leetcode/Array/leetcode215.py
- members/U02BQ6G1SQJ/leetcode/Array/leetcode417.py
- members/U02BQ6G1SQJ/programmers/weeklychallenge/최소직사각형.py
<head>
<style>
</style>
</head>
215. Kth   Largest Element in an Array |   | 59.90% | Medium | 10 | 09/28(Tue)
417. Pacific   Atlantic Water Flow |   | 45.00% | Medium | 10 | 09/28(Tue)
</body>
</html>
> 2021-09-28 Jade

- members/U02BQ6G1SQJ/leetcode/Hash_Table/leetcode49.py
- members/U02BQ6G1SQJ/leetcode/Tree/leetcode1448.py
<head>
<style>
</style>
</head>
49. Group Anagrams |   | 60.60% | Medium | 10 | 09/30(Thu)
1448. Count   Good Nodes in Binary Tree |   | 72.00% | Medium | 11 | 09/30(Thu)
</body>
</html>
> 2021-09-30 Jade

- members/U02BQ6G1SQJ/leetcode/Array/leetcode695.py
- members/U02BQ6G1SQJ/leetcode/Math/leetcode528.py
<head>
<style>
</style>
</head>
695. Max Area of   Island |   | 66.70% | Medium | 11 | 10/01(Fri)
528. Random   Pick with Weight |   | 45.00% | Medium | 12 | 10/01(Fri)
</body>
</html>
> 2021-10-01 Jade

- members/U02BQ6G1SQJ/leetcode/Array/leetcode1277.py
- members/U02BQ6G1SQJ/leetcode/Array/leetcode54.py
<head>
<style>
</style>
</head>
54. Spiral Matrix |   | 37.40% | Medium | 13 | 10/03(Sun)
1277. Count   Square Submatrices with All Ones |   | 73.10% | Medium | 14 | 10/03(Sun)
</body>
</html>
> 2021-10-03 Jade

- members/U02BQ6G1SQJ/leetcode/Hash_Table/leetcode139.py
- members/U02BQ6G1SQJ/leetcode/Hash_Table/leetcode17.py
<head>
<style>
</style>
</head>
139. Word Break |   | 42.50% | Medium | 14 | 10/05(Tue)
17. Letter   Combinations of a Phone Number |   | 50.70% | Medium | 14 | 10/05(Tue)
</body>
</html>
> 2021-10-05 Jade

- members/U02BQ6G1SQJ/leetcode/Array/leetcode1423.py
- members/U02BQ6G1SQJ/leetcode/Array/leetcode1428.py
<head>
<style>
</style>
</head>
1423. Maximum   Points You Can Obtain from Cards |   | 48.60% | Medium | 15 | 10/06(Wed)
1428. Leftmost   Column with at Least a One |   | 50.20% | Medium | 16 | 10/06(Wed)
</body>
</html>
> 2021-10-06 Jade

- members/U02BQ6G1SQJ/leetcode/Array/leetcode57.py
- members/U02BQ6G1SQJ/leetcode/Array/leetcode621.py
<head>
<style>
</style>
</head>
57. Insert Interval |   | 35.90% | Medium | 18 | 10/09(Sat)
621. Task Scheduler |   | 52.80% | Medium | 18 | 10/09(Sat)
</body>
</html>
> 2021-10-10 Jade

- members/U02BQ6G1SQJ/leetcode/Array/leetcode1570.py
- members/U02BQ6G1SQJ/leetcode/Array/leetcode721.py
<head>
<style>
</style>
</head>
1570. Dot   Product of Two Sparse Vectors |   | 91.00% | Medium | 25 | 10/30(Sat)
721. Accounts Merge |   | 53.10% | Medium | 25 | 10/30(Sat)
</body>
</html>
> 2021-10-30 Jade

- members/U02BQ6G1SQJ/leetcode/Array/leetcode1578.py
- members/U02BQ6G1SQJ/leetcode/Array/leetcode1631.py
<head>
<style>
</style>
</head>
1578. Minimum   Deletion Cost to Avoid Repeating Letters |   | 61.00% | Medium | 29 | 10/31(Sun)
1631. Path   With Minimum Effort |   | 50.20% | Medium | 29 | 10/31(Sun)
</body>
</html>
> 2021-10-31 Jade

- members/U02BQ6G1SQJ/BOJ/implementation/BOJ10809.py
- members/U02BQ6G1SQJ/BOJ/implementation/BOJ2741.py
- members/U02BQ6G1SQJ/BOJ/implementation/BOJ2742.py
- members/U02BQ6G1SQJ/BOJ/implementation/BOJ9498.py
- members/U02BQ6G1SQJ/BOJ/mathematics/BOJ10871.py
- members/U02BQ6G1SQJ/BOJ/mathematics/BOJ1546.py
- members/U02BQ6G1SQJ/BOJ/mathematics/BOJ2753.py
- members/U02BQ6G1SQJ/BOJ/mathematics/BOJ2884.py
- members/U02BQ6G1SQJ/BOJ/mathematics/BOJ2908.py
- members/U02BQ6G1SQJ/BOJ/mathematics/BOJ3052.py
<head>
<style>
</style>
</head>
1546. 평균 |   |   | Class 1 |   | 11/01(Mon)
2741. N 찍기 |   |   | Class 1 |   | 11/01(Mon)
2742. 기찍 N |   |   | Class 1 |   | 11/01(Mon)
2753. 윤년 |   |   | Class 1 |   | 11/01(Mon)
2884. 알람 시계 |   |   | Class 1 |   …
> 2021-11-01 Jade

- members/U02BQ6G1SQJ/leetcode/Array/leetcode986.py
- members/U02BQ6G1SQJ/leetcode/Tree/leetcode236.py
<head>
<style>
</style>
</head>
236. Lowest   Common Ancestor of a Binary Tree |   | 50.90% | Medium | 30 | 11/05(Fri)
986. Interval   List Intersections |   | 68.90% | Medium | 30 | 11/05(Fri)
</body>
</html>
> 2021-11-05 Jade

- members/U02BQ6G1SQJ/leetcode/Graph/leetcode323.py
- members/U02BQ6G1SQJ/leetcode/Two_Pointers/leetcode151.py
<head>
<style>
</style>
</head>
151. Reverse   Words in a String |   | 24.90% | Medium | 31 | 11/06(Sat)
323. Number   of Connected Components in an Undirected Graph |   | 58.80% | Medium | 31 | 11/06(Sat)
</body>
</html>
> 2021-11-06 Jade

- members/U02BQ6G1SQJ/leetcode/Array/leetcode833.py
- members/U02BQ6G1SQJ/leetcode/Linked_List/leetcode426.py
<head>
<style>
</style>
</head>
426. Convert   Binary Search Tree to Sorted Doubly Linked List |   | 62.20% | Medium | 31 | 11/07(Sun)
833. Find   And Replace in String |   | 51.80% | Medium | 31 | 11/07(Sun)
</body>
</html>
> 2021-11-07 Jade

- members/U02BQ6G1SQJ/leetcode/Array/leetcode1091.py
- members/U02BQ6G1SQJ/leetcode/Tree/leetcode103.py
<head>
<style>
</style>
</head>
103. Binary   Tree Zigzag Level Order Traversal |   | 51.10% | Medium | 32 | 11/09(Tue)
1091. Shortest   Path in Binary Matrix |   | 40.60% | Medium | 32 | 11/09(Tue)
</body>
</html>
> 2021-11-09 Jade

- members/U02BQ6G1SQJ/leetcode/String/leetcode211.py
- members/U02BQ6G1SQJ/leetcode/String/leetcode418.py
<head>
<style>
</style>
</head>
211. Design   Add and Search Words Data Structure |   | 41.40% | Medium | 32 | 11/12(Fri)
418. Sentence   Screen Fitting |   | 34.10% | Medium | 32 | 11/12(Fri)
</body>
</html>
> 2021-11-12 Jade

- members/U02BQ6G1SQJ/leetcode/Hash_Table/leetcode1650.py
- members/U02BQ6G1SQJ/leetcode/Hash_Table/leetcode299.py
<head>
<style>
</style>
</head>
1650. Lowest   Common Ancestor of a Binary Tree III |   | 76.90% | Medium | 33 | 11/13(Sat)
299. Bulls and Cows |   | 45.20% | Medium | 33 | 11/13(Sat)
</body>
</html>
> 2021-11-13 Jade

- members/U02BQ6G1SQJ/leetcode/Array/leetcode1465.py
- members/U02BQ6G1SQJ/leetcode/Array/leetcode523.py
<head>
<style>
</style>
</head>
1465. Maximum   Area of a Piece of Cake After Horizontal and Vertical Cuts |   | 36.70% | Medium | 34 | 11/14(Sun)
523. Continuous   Subarray Sum |   | 25.30% | Medium | 34 | 11/14(Sun)
</body>
</html>
> 2021-11-14 Jade

- members/U02BQ6G1SQJ/leetcode/Array/leetcode1167.py
- members/U02BQ6G1SQJ/leetcode/Tree/leetcode652.py
<head>
<style>
</style>
</head>
652. Find   Duplicate Subtrees |   | 53.80% | Medium | 34 | 11/15(Mon)
1167. Minimum   Cost to Connect Sticks |   | 65.40% | Medium | 35 | 11/15(Mon)
</body>
</html>
> 2021-11-15 Jade

- members/U02BQ6G1SQJ/leetcode/Hash_Table/leetcode314.py
- members/U02BQ6G1SQJ/leetcode/Tree/leetcode545.py
<head>
<style>
</style>
</head>
545. Boundary   of Binary Tree |   | 41.10% | Medium | 35 | 11/17(Wed)
314. Binary   Tree Vertical Order Traversal |   | 47.80% | Medium | 36 | 11/17(Wed)
</body>
</html>
> 2021-11-17 Jade

- members/U02BQ6G1SQJ/leetcode/Math/leetcode1344.py
- members/U02BQ6G1SQJ/leetcode/String/leetcode1328.py
<head>
<style>
</style>
</head>
1328. Break a   Palindrome |   | 49.10% | Medium | 37 | 11/18(Thu)
1344. Angle   Between Hands of a Clock |   | 61.50% | Medium | 37 | 11/18(Thu)
</body>
</html>
> 2021-11-18 Jade

- members/U02BQ6G1SQJ/leetcode/Depth-First_Search/leetcode947.py
- members/U02BQ6G1SQJ/leetcode/Math/leetcode29.py
<head>
<style>
</style>
</head>
29. Divide Two   Integers |   | 17.00% | Medium | 37 | 11/19(Fri)
947. Most   Stones Removed with Same Row or Column |   | 55.90% | Medium | 37 | 11/19(Fri)
</body>
</html>
> 2021-11-19 Jade

- members/U02BQ6G1SQJ/leetcode/Array/leetcode353.py
- members/U02BQ6G1SQJ/leetcode/String/leetcode1647.py
- members/U02BQ6G1SQJ/programmers/weeklychallenge/아이템 줍기.py
<head>
<style>
</style>
</head>
1647. Minimum   Deletions to Make Character Frequencies Unique |   | 55.80% | Medium | 38 | 11/26(Fri)
353. Design Snake   Game |   | 36.70% | Medium | 38 | 11/26(Fri)
</body>
</html>
> 2021-11-26 Jade

- members/U02BQ6G1SQJ/leetcode/Math/leetcode837.py
- members/U02BQ6G1SQJ/leetcode/Two_Pointers/leetcode277.py
<head>
<style>
</style>
</head>
837. New 21 Game |   | 35.70% | Medium | 38 | 11/29(Mon)
277. Find the   Celebrity |   | 44.60% | Medium | 39 | 11/29(Mon)
</body>
</html>
> 2021-11-29 Jade

- members/U02BQ6G1SQJ/leetcode/Array/leetcode454.py
- members/U02BQ6G1SQJ/leetcode/String/leetcode1525.py
<head>
<style>
</style>
</head>
454. 4Sum II |   | 55.00% | Medium | 39 | 11/30(Tue)
1525. Number   of Good Ways to Split a String |   | 68.90% | Medium | 40 | 11/30(Tue)
</body>
</html>
> 2021-11-30 Jade

- members/U02BQ6G1SQJ/leetcode/Array/leetcode1762.py
- members/U02BQ6G1SQJ/leetcode/Graph/leetcode490.py
<head>
<style>
</style>
</head>
1762. Buildings   With an Ocean View |   | 81.40% | Medium | 40 | 12/01(Wed)
490. The Maze |   | 53.40% | Medium | 40 | 12/01(Wed)
</body>
</html>
> 2021-12-01 Jade

- members/U02BQ6G1SQJ/leetcode/Array/leetcode1239.py
- members/U02BQ6G1SQJ/leetcode/Array/leetcode1648.py
<head>
<style>
</style>
</head>
1239. Maximum   Length of a Concatenated String with Unique Characters |   | 50.50% | Medium | 41 | 12/02(Thu)
1648. Sell   Diminishing-Valued Colored Balls |   | 31.30% | Medium | 41 | 12/02(Thu)
</body>
</html>
> 2021-12-02 Jade

- members/U02BQ6G1SQJ/leetcode/Array/leetcode562.py
- members/U02BQ6G1SQJ/leetcode/Dynamic_Programming/leetcode894.py
<head>
<style>
</style>
</head>
894. All   Possible Full Binary Trees |   | 77.90% | Medium | 41 | 12/05(Sun)
562. Longest   Line of Consecutive One in Matrix |   | 47.10% | Medium | 42 | 12/05(Sun)
</body>
</html>
> 2021-12-05 Jade

- members/U02BQ6G1SQJ/leetcode/Array/leetcode1706.py
- members/U02BQ6G1SQJ/leetcode/Array/leetcode934.py
<head>
<style>
</style>
</head>
1706. Where   Will the Ball Fall |   | 63.00% | Medium | 43 | 12/06(Mon)
934. Shortest   Bridge |   | 50.70% | Medium | 43 | 12/06(Mon)
</body>
</html>
> 2021-12-06 Jade

- members/U02BQ6G1SQJ/leetcode/Array/leetcode1254.py
- members/U02BQ6G1SQJ/leetcode/Tree/leetcode1120.py
<head>
<style>
</style>
</head>
1120. Maximum   Average Subtree |   | 64.50% | Medium | 44 | 12/07(Tue)
1254. Number   of Closed Islands |   | 62.20% | Medium | 44 | 12/07(Tue)
</body>
</html>
> 2021-12-07 Jade

- members/U02BQ6G1SQJ/leetcode/Array/leetcode249.py
- members/U02BQ6G1SQJ/leetcode/Array/leetcode658.py
<head>
<style>
</style>
</head>
249. Group   Shifted Strings |   | 59.20% | Medium | 44 | 12/08(Wed)
658. Find K   Closest Elements |   | 42.80% | Medium | 44 | 12/08(Wed)
</body>
</html>
> 2021-12-08 Jade

- members/U02BQ6G1SQJ/leetcode/Linked_List/leetcode708.py
- members/U02BQ6G1SQJ/leetcode/Math/leetcode1628.py
<head>
<style>
</style>
</head>
1628. Design   an Expression Tree With Evaluate Function |   | 80.90% | Medium | 45 | 12/09(Thu)
708. Insert   into a Sorted Circular Linked List |   | 32.90% | Medium | 45 | 12/09(Thu)
</body>
</html>
> 2021-12-09 Jade

- members/U02BQ6G1SQJ/leetcode/Array/leetcode722.py
- members/U02BQ6G1SQJ/leetcode/Union_Find/leetcode1135.py
<head>
<style>
</style>
</head>
1135. Connecting   Cities With Minimum Cost |   | 60.00% | Medium | 46 | 12/11(Sat)
722. Remove   Comments |   | 36.80% | Medium | 46 | 12/11(Sat)
</body>
</html>
> 2021-12-11 Jade

- members/U02BQ6G1SQJ/leetcode/Array/leetcode1429.py
- members/U02BQ6G1SQJ/leetcode/Array/leetcode900.py
<head>
<style>
</style>
</head>
900. RLE Iterator |   | 56.40% | Medium | 46 | 12/13(Mon)
1429. First   Unique Number |   | 50.40% | Medium | 47 | 12/13(Mon)
</body>
</html>
> 2021-12-13 Jade

- members/U02BQ6G1SQJ/leetcode/Graph/leetcode1615.py
- members/U02BQ6G1SQJ/leetcode/Hash_Table/leetcode398.py
<head>
<style>
</style>
</head>
1615. Maximal   Network Rank |   | 54.10% | Medium | 47 | 12/15(Wed)
398. Random Pick   Index |   | 59.40% | Medium | 47 | 12/15(Wed)
</body>
</html>
> 2021-12-15 Jade

- members/U02BQ6G1SQJ/leetcode/Tree/leetcode117.py
- members/U02BQ6G1SQJ/leetcode/Tree/leetcode951.py
<head>
<style>
</style>
</head>
117. Populating   Next Right Pointers in Each Node II |   | 43.10% | Medium | 48 | 12/16(Thu)
951. Flip   Equivalent Binary Trees |   | 66.00% | Medium | 48 | 12/16(Thu)
</body>
</html>
> 2021-12-16 Jade

- members/U02BQ6G1SQJ/leetcode/Array/leetcode957.py
- members/U02BQ6G1SQJ/leetcode/Tree/leetcode1376.py
<head>
<style>
</style>
</head>
1376. Time   Needed to Inform All Employees |   | 57.20% | Medium | 49 | 12/17(Fri)
957. Prison   Cells After N Days |   | 40.00% | Medium | 49 | 12/17(Fri)
</body>
</html>
> 2021-12-17 Jade

- members/U02BQ6G1SQJ/leetcode/Array/leetcode1730.py
- members/U02BQ6G1SQJ/leetcode/Array/leetcode915.py
<head>
<style>
</style>
</head>
1730. Shortest   Path to Get Food |   | 54.50% | Medium | 50 | 12/18(Sat)
915. Partition   Array into Disjoint Intervals |   | 47.10% | Medium | 50 | 12/18(Sat)
</body>
</html>
> 2021-12-18 Jade

- members/U02BQ6G1SQJ/leetcode/Array/leetcode1275.py
- members/U02BQ6G1SQJ/leetcode/Array/leetcode1304.py
- members/U02BQ6G1SQJ/leetcode/Array/leetcode35.py
- members/U02BQ6G1SQJ/leetcode/Array/leetcode766.py
- members/U02BQ6G1SQJ/leetcode/SQL/leetcode1421.sql
- members/U02BQ6G1SQJ/leetcode/String/leetcode1047.py
- members/U02BQ6G1SQJ/leetcode/Two_Pointers/leetcode408.py
- members/U02BQ6G1SQJ/leetcode/Two_Pointers/leetcode696.py
올해 마지막 PR!
2021-12-24 기준 지금까지 푼 문제 수 : 940문제
백준 502문제
리트코드 244문제
프로그래머스 136문제
SW Expert Academy 58문제
모두 메리 크리스마스~
> 2021-12-24 Jade
